### ISSUE TITLE
Pre-Draft Checklist

### ISSUE THREAD

**Issue by siv2r** [siv2r/bip-frost-signing#3]
### Mandatory
- [ ]  Identifying Disruptive Signers (Overview)
    - [ ]  create partialsig forgery doc
    - [ ]  formalize problems by using the participant identifier instead of an index
- [ ]  Fix Footnotes TODOs
- [ ]  Dealing with Infinity Nonce (Remarks)
- [ ]  Nonce Size (Remarks)
- [ ]  Check FROST RFC (mainly security consideration) for additional points

### Bonus
- [ ]  Reference code for the stateless signer
- [ ] Sync terminology with DKG
- [ ] Nonce generation hash params
    - [ ]  normal: can we include participant identifiers too?
    - [ ]  stateless: include pubshare too? (musig2 doesn't include pubkey)
